/// Flutter icons Food
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Food
///      fonts:
///       - asset: fonts/Food.ttf
///
///
///
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class FoodIcons {
  FoodIcons._();

  static const _kFontFam = 'Food';
  static const String? _kFontPkg = null;

  static const IconData hand =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bowl =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData knife =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData oven =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spoon =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tray =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wisk =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static IconData getIcon(String name) {
    switch (name) {
      case 'hand':
        return FoodIcons.hand;
      case 'oven':
        return FoodIcons.oven;
      case 'knife':
        return FoodIcons.knife;
      case 'tray':
        return FoodIcons.tray;
      case 'wisk':
        return FoodIcons.wisk;
      case 'spoon':
        return FoodIcons.spoon;
      case 'bowl':
        return FoodIcons.bowl;
      default:
        return Icons.error;
    }
  }
}
